import json
import random

# This script is designed to generate a dataset for a
# machine learning algorithm that aims to decipher
# the unique terminology used by an options trader
# named Casey. The purpose of writing this program is
# to facilitate a better understanding of Casey's
# specific trading language and context, enabling
# improved analysis and decision-making when working
# with their strategies. By creating a comprehensive
# dataset based on Casey's communication style, the
# machine learning model will be able to effectively
# recognize and interpret their statements, ultimately
# enhancing the user's ability to collaborate with
# Casey in the options market.

buy = (
    "I took the 309c for a riskier trade here",
    "I’m taking these  qqq 309c @ .48",
    "taking these @ .56",
    "I’m taking spy 395p @ .66",
    "I’m taking qqq .44",
    "I’m taking spy 392p @ .74",
    "I’m taking qqq 301p @ . 60",
    "I’m taking spy 388p @ .54",
    "I’m taking spy 387p @ .50",
    "I’m taking Iwm 171p @ .45",
    "I’m in qqq 306c here @ .44",
    "I’m taking qqq 306c here @ .50 again",
    "I’m taking qqq 306c @ .46 again",
    "I’m took these here",
    "Fill was .46",
    "I’m taking AMD 96c @ .57",
    "I’m back in the 390c",
    "I’m taking spy 390c @ .62",
    "I’m taking qqq 298c @ .30",
    "I’m taking these @ .66",
    "I’m taking spy 382p @ .71",
    "I’m taking spy 383p @ .75",
    "I’m taking spy 1dte 385p @ 1.00",
    "I’m taking these at .54",
    "I’m taking spy 390p @ .40",
    "I’m taking qqq 298c @ .81",
    "I’m taking qqq 298c @ .65",
    "I’m taking spy 394c @ .62",
    "I’m taking spy 394c @ .66",
    "I’m taking these qqq 294c here @ .60",
    "I’m taking Iwm 172p @ .55",
    "I’m taking Iwm 172p @ .60",
    "I’m taking qqq 295c @ .71",
    "I’m taking qqq 295c @ .60",
    "I’m taking Iwm 177p @ .50",
    "I’m taking spy 394p @ .43",
    "I’m taking spy 398p here",
    "I’m taking spy 398p @ .56",
    "I’m taking spy 399p @ .73",
    "I’m taking qqq 299p @ .70",
    "I’m taking spy 397p @ .33",
    "taking these @ .50",
    "I’m taking spy 1dte 396p @ .75",
    "I’m taking spy 398p @ .53",
    "I’m taking spy 398p @ .64",
    "I’m taking spy 399p @ .54",
    "QQQ 271c @ 1.00",
    "QQQ 273c @ .82",
    "nvda 135c @ .98",
    "Iwm 176c @ 1.20",
    "qqq 277p @ .74",
    "nvda 122p @ .75",
    "amd 64p @ .90",
    "qqq 280c @ .75",
    "tsla 252.5c @ 1.00",
    "meta 134p @ .95",
    "meta 145c @ .57",
    "Iwm 172p @ .90",
    "tsla 225p @ .63",
    "apple 141p @ .65",
    "spy 364p @ .71",
    "spy 364p @ .90",
    "took these 269p @ .43 with a -10% stop set",
    "Stop on qqq is .65 for me here",
    "amd 54p @ .95",
    "qqq 264p @ .60",
    ".73 here on qqq",
    "spy 359p @ .57",
    "spy 357p @ .35",
    "apple 145c @ 1.13",
    "Iwm 165p @ .54",
    "Iwm 165p @ .54",
    "qqq 266c @ .65",
    "Spy @ .70 on the 356",
    "Amd 60c @ .62",
    "apple 144c @ .38",
    "nvda 121c @ 1.07",
    "amd 57p @ .50",
    "I took qqq 263 @ .70",
    "qqq 261p @ .65",
    "Spy 357p @ .52",
    "nvda 125c @ 1.02",
    "Iwm 173c @ .59",
    "Iwm 179c @ .70",
    "amd 57p @ .90",
    "spy 364p @ .89",
    "apple 140p @ 1.35",
    "spy 365p @ .47",
    "Iwm 170p @ .36",
    "qqq 275c @ .70",
    "I bought more of these at .60 so now I have a .65 average",
    "spy 366p @ .75",
    "Iwm 168p @ .14",
    "I took some apple 145c @ 1.10 here",
    "tsla 192.5p @ 1.28",
    "I’m getting back in these tsla 192.5p @ .45 here",
    "qqq 267p @ 1.12",
    "Iwm 172c @ .50",
    "I’m entering spy 370c @ .91 here",
    "qqq 270p @ .47",
    "I took these qqq 270p @ .25 here",
    "spy 379c @ .51",
    "I’m taking Iwm 174c @ .39",
    "I’m taking spy 376p here @ .46. It’s a little risky imo",
    "I’m taking Iwm 172p @ .21",
    "I’m taking qqq 278c here @ .63",
    "I took these qqq 287c @ 1.07",
    "I took the amd 63c @ .83",
    "I’m trying spy 388c @ .90",
    "spy 380p @ 1.14",
    "spy puts at 1.25 here raising my stop to b/e",
    "I’m trying these 180c here at the 200",
    "I got Iwm 180c here @ .45 on the pm high hold",
    "I’m getting these 385c here @ .95",
    "spy 387c @ .68",
    "amd 62c @ 1.05",
    "I’m gonna try down qqq 284c @ .65 here it’s a little risky imo",
    "I took amd 64c @ .56",
    "I took nvda 140c @ .55",
    "I took spy 375p @ .92 here",
    "I got back in spy these puts here @ .70",
    "apple 140p @ 1.24",
    "I took qqq 270p @ 1.18",
    "I took qqq 277c @ .85",
    "I took tsla 215p on that retest. I’ll get more on the next",
    "I’m getting the 215p on tsla at .80 here",
    "I’m scalping these 215p on tsla again at .28",
    "I took tsla 217.5p @ .42",
    "I’m taking these 227.5c on tsla @ .47",
    "I’m taking tsla 227.5c @ .65",
    "I took qqq 276p @ .62",
    "I got some qqq 275p here @ .45",
    "I took the 276p @ .72",
    "I took these @ .93",
    "I took these 389c @ .52",
    "I’m taking these 385p here @ .59",
    "i took Iwm 184c @ .35",
    "I took qqq 271p @ 1.05",
    "I’m taking spy 378p @ 1.18",
    "I’m trying these tsla 215p @ 1.30",
    "I’m taking these 279p here @ 1.02",
    "I got Iwm 188c @ .76",
    "qqq 269p @ .77",
    "I’m taking msft 220p @ 1.25",
    "I took spy 363p here @ the 48 ema",
    "Iwm 172p @ .40",
    "I took these 268c here @ 1.28",
    "I’m in these @ .50",
    "I’m taking qqq 257p @ .90",
    "I took spy 378c @ 1.15",
    "I’m taking spy 368p @ 1.15",
    "I’m taking nvda 142c @ .93",
    "Iwm 180c @ .60",
    "I’m trying nvda 142c here again @ .42",
    "I took these apple 136p @ .40",
    "qqq 258p @.21",
    "Im taking qqq 262p @ .59",
    "I’m taking Iwm 177p here @ .38",
    "I’m taking Iwm 177p here @ .25",
    "I took Iwm 178p here",
    "spy 380c @ .50",
    "I took wed. Iwm 182c @ .80",
    "I’m taking tsla 175p @ 1.60",
    "I’m taking amzn 135p here @ 1.03",
    "I’m getting these Iwm 182c @ .94",
    "I’m taking qqq 275c @ 1.10",
    "I’m taking these qqq 275c again here @ 1.21",
    "Okay I closed it here for -8",  #############################################
    "I’m taking Iwm 176p @ .54",
    "Took the spy 377p @ .49",
    "I took meta 107c @ 1.00",
    "I took spy 377p @ .65",
    "I’m taking Iwm at the 200ema 177p @ .38",
    "I’m adding Iwm 176p here as well",
    "Added more here",
    "I’m taking spy 377p of the 13ema here @ .76",
    "I’m taking spy 394c @ .93",
    "I’m taking these spy 394c here @ 1.24",
    "I’m taking apple 143p @ .40",
    "I’m taking Apple 144p",
    "I took Iwm 189c @ .59",
    "I took qqq 287c @ .65",
    "I’m taking spy 392p here @ .40",
    "I’m in @ 1.10 here on tsla",
    "Scaling some here @ 25%",
    "I’m taking spy 399c @ .42",
    "I’m taking Iwm 184p @ .42",
    "I’m taking qqq 284p @ .95",
    "I’m taking qqq 284p @ .53",
    "I took qqq 288c @ .72",
    "I took qqq 289c @ .40",
    "Locked some at .49 here",   #################################################
    "I’m taking these Spy 400c @ .75",
    "I’m trying Iwm 187c here at the 48ema @ .46",
    "switching short here on Iwm. I got some 186p @ .09",
    "spy 405c @ .50, Riskier trade here",
    "I’m taking Iwm 191c @ .68",
    "I’m in @ .66",
    "I’m taking spy 399p @ .78",
    "back in 399p @ .56",
    "I’m getting qqq 284p here @ .35",
    "back in qqq here at  .39 average",
    "I’m taking qqq 291c here @ .32, Risky play here",
    "I’m taking qqq 284p @ .55",
    "I’m getting in Iwm 184p here @ .58",
    "I’m taking these qqq 284p again here @ .77",
    "taking spy 394p @ .65",
    "I’m taking spy 399c @ .33",
    "I’m taking Iwm 184p @ .42",
    "I’m getting in qqq 285p @ .55 here",
    "I’m taking these spy 390p @ .48",
    "taking nvda 152.5p @ .53",
    "back in nvda 152.5p @ .41",
    "amd 73p @ .46",
    "I’m taking these qqq 282p @ .50",
    "I’m taking spy 393p @ .35",
    "I’m taking qqq 301p @ . 60",
    "I’m taking spy 392p @ .74",
    "I’m taking qqq .44",
    "I’m taking spy 395p @ .66",
    "taking these @ .56",
    "I’m taking these  qqq 309c @ .48",
    "I took the 309c for a riskier trade here",
    "I’m took qqq 313c here",
    "Taking these at .75",
    "I’m taking spy 400c @ .50",
    "I’m taking spy 394p @ .55",
    "I’m back in these spy 394p @ .54",
    "I’m taking spy 389p 1dte @ .88",
    "taking spy 388p @ .73",
    "I’m taking spy 395c @ .56",
    "I got the 395c @ .61",
    "I’m taking qqq 310c here",
    "I’m taking these @ .63",
    "I’m taking 1dte qqq 313c @ .93"
)

sell = (
    "This candle stopped me out. I’m out now",
    "I’m out here",
    "scaled some",
    "selling the east here at even",
    "scaling some here on this drop",
    "stop hit here",
    "stopped out here",
    "I’m out most at our 200ema target 🎯 110%",
    "Really nice move . I’m out half for 40%",
    "I’m taking a little off here",
    "I’m out of qqq here",
    "stop hit here",
    "out half over 20% here",
    "I’m out of spy",
    "I’m out half here @ 30%",
    "my stop hit there I’m out of Iwm",
    "I trimmed some @ 55%",
    "sold some here @ 25%",
    "I’m out here on qqq, getting late in the day",
    "I’m out half @ 40%",
    "stopped out here",
    "I’m out half @ 20% here",
    "I’m out of qqq here @ .46",
    "scaling some here",
    "I’m taking profits on amd here. I’m out",
    "Here’s 20% on qqq trimming some and keeping it green",
    "I’m out half @ 60%",
    "I’m out of spy",
    "I’m out here",
    "sold half @ 25%",
    "I’m out here",
    "I’m selling some here @ .35",
    "I’m out here",
    "I’m out half @ 20%",
    "I’m out half @ 20%",
    "my Stop hit on that bounce",
    "I trimmed some here @ 40%",
    "I’m out half at 20%",
    "okay I stopped out here at the 13ema",
    "I’m out of spy",
    "I’m out half @ .75",
    "I’m out of spy",
    "nice break down here, I’m out half here",
    "I’m out here",
    "I’m out here",
    "Here’s the new high of day. I took more off here",
    "I’m out of spy here",
    "I’m out half here at the new high of day!",
    "Scaled some",
    "selling the east here at even, sorry meant rest not east",
    "I’m out half at 25%",
    "I’m out here",
    "out half at 20%",
    "I’m out of Iwm here",
    "I’m scaling some here",
    "I’m out of Iwm here",
    "took a little more off @ 40%",
    "nearing 20% already here. Won’t let this go red",
    "There’s over 20% I scaled some",
    "stopped out here on the rest",
    "out half here near 20%",
    "stopped out of qqq now",
    "Scaled some at the high",
    "I’m out half here @ 30%",
    "scaling some at 20% here",
    "I’m out here for 100% at our target",
    "I’m out of spy here",
    "I’m out half here @ 50%",
    "I’m out of spy",
    "scaled some of the 398p there",
    "Qqq at support so I scaled more",
    "out half at 30% here",
    "I’m out here",
    "I’m out of spy here",
    "I’m out half @ 20%",
    "I’m out here",
    "new low day here! 50% now I’m scaling",
    "scaled some",
    "Can’t hold through these candles. I’m out",
    "New lows here! Scaling some @ 50%",
    "taking some off here @ 20%",
    "my stop hit",
    "Nice move already! Scaling some out",
    "I’m out here",
    "there that new low 🔥 Scaling out",
    "I’m out of qqq here",
    "selling half here at 25%",
    "55% here I’m scaling more",
    "85% trail your stop tight",
    "scaling some at 1.05 here",
    "30% here, raise stops and protect those gains",
    "taking most of my position off here at 60%",
    "Stop hit on QQQ",
    "stop at b/e on nvda",
    "scaled some nvda @ .90",
    "scaling some @ 25% here to be safe",
    "taking all gains here at 1.90",
    "scaling half of tsla at 1.20",
    "that stop hit for me",
    "Keep a -10% stop",
    "selling half here @ 1.05",
    "selling half here @ .73 and raising my stop to break even",
    "I got stopped out at .80 on tsla 👍",
    "stopped out of apple here. Will re assess",
    "scaling some spy puts @ 35%",
    "Stopped out at 1.00 here 🔥",
    "13 broke I’m stopping out",
    "35% here scale some!",
    "I scaled a little here @ 1.03 raising my stop to break even now. Playing safe",
    "Break even stop hit on amd",
    "I’m selling half here @ 30%",
    "selling half at 25% here",
    "60% on spy. Scale out and keep stops raised",
    "selling some spy @ 20% here",
    "I placed a stop on apple at 1.00",
    "Keep a 20% stop",
    "Keep a 15% stop here",
    "scaling half on this pop to .78",
    "70% trailing my stop and riding it up",
    "selling half at .50",
    "selling half of nvda @ 1.30",
    "Trimming some amd @ .62",
    ".95 on here. Make sure you lock in those gains",
    "selling some qqq @ .85",
    "We’re over 50% gains here. Trail your stop behind to protect those gains",
    "85% on qqq here @ 1.25 lock most of those gains in",
    "100% here 🔥",
    ".62 here stop is at break even, no risk trade",
    "-10% stop on these",
    "trimming alittle here @ .65 staying safe",
    ".75 here on Iwm keep the stops in the profit",
    "I trimmed a little Iwm back @ .74 the overall market looks weak so play it safe",
    "Stop is .80 for me on amd",
    "@ 1.50 here I raised my stop to break even",
    "Now @ 1.60 I’m just gonna trail my stop behind to keep it green and try to ride this out",
    "40% I’m selling half on spy",
    "@ 60% as we approach the pml. Could see a bounce so be careful. Trail your stop",
    "Iwm @ 20% here don’t let it go red",
    "Stopped out",
    "over 50% here raise your stops",
    "100% nice!",
    "I’m stopping out of these. Will re assess",
    "Playing it safe here. We don’t need to give back any gains from earlier",
    "These are at .52 now and my stop is above the 200ema",
    "Stopped out on tsla",
    "stopped out of spy here",
    "These are at 12% my stop is gonna be above the pm low",
    "I’m selling a few of these qqq puts at .30 here incase we bounce at the 13ema",
    "Scaling half @ 30% here",
    "Raise your stops",
    "I sold half here @ 50%",
    "Target 🎯 approaching here. Locked in more @ 60%. Holding some for a 200ema break if we can get it",
    "Iwm finally breaking these emas. I’m cutting it",
    "scaling a little @ 30% here on this pop",
    "45% here on qqq I’m raising my stop on some more contracts",
    "Scaled most at 85% here",
    "100% here on qqq 🔥",
    "im scaling some here @ 1.23",
    "Stop is set at entry price for a risk free ride now",
    "I but amd, doesn’t appear to be holding up for now",
    "I’m scaling some early here at 1.00 to reduce some risk",
    "Sold the rest of my spy cons here. There moving so slow to the upside",
    "We’re over 1.30 on these puts, I’m just gonna trail my stop and aim for the 200ema. It’s a long way down there so we will see what happened here",
    "Looks like we’re not getting that 200ema test here. Nice little base hit here",
    "These are @ 30% here I have a stop at b/e now",
    "I’m scaling some here @ the pm high",
    "selling half @ .55 here",
    "Scaling some here @ 1.15",
    "almost 40% on this candle, trailing my stop",
    "My stop both Iwm and spy hit, .60 on Iwm and 1.30 on spy. Nice trades on both",
    "My stop hit on these spy calls",
    "That candle stopped me out. It was definitely a risky trade",
    "Scaled some there @ 25%",
    "nvda looking weak, set stop on amd",
    "Stopped out of nvda here @ 60%",
    "Amd got stopped out as well",
    "This push up on spy stopped me out",
    "Selling spy here",
    "I’m scaling some on this big push down",
    "I’m selling some apple @ 1.45 reducing risk",
    "25% on apple here I’m trailing my stop and locking some in",
    "I’m taking some gains on apple at 40% here",
    "trailing stop hit here on apple. Was up 58% and set it tight",
    "selling some at 1.35 here",
    "now we are up over 20% on qqq, protect your gains by trailing your stops. We should see a nice grind down imo",
    "I’m scaling some here @ 1.00",
    "Stopped on this candle for the rest",
    "30% already I’m scaling and raising stops",
    "Stopped at break here on the rest of tsla",
    "70% here I’m scaling some",
    "Stop hit at even on the rest",
    "Scaling some @ 20% here to make it a safer play",
    "Perfect entry, scaling some @ .90 here",
    "Stopped at even on the rest",
    "20% on qqq here I’m raising my stop",
    "above 30% here I’m taking my first scale",
    "60% here on qqq I’m scaling more",
    "Scaling some here @ 40%",
    "scaled some there @ 25% letting the rest ride",
    "I stopped out on these. It’s not holding",
    "Scaling some here @ .72",
    "That stop hit, I may re enter",
    "Wow major candle! Stopped out there",
    "I’m selling half @ 1.25",
    "Spy at 20% I’m scaling some on both",
    "Stops hit on these",
    "Stopped out here on tsla",
    "I’m going to sell these here at b/e due to the sideways action on this move",
    "Scaling @.85",
    "Stopped on the rest here",
    "Scaling some here over 1.30",
    "Selling msft, no follow through here",
    "Scaling some here at .49 @ the 13ema",
    "First scale is here at this 371 level",
    "If we break this level we should get a nice move on these",
    "Scaling some at 1.05 here",
    "I’m cutting the rest of qqq here, this move is taking to long",
    "I cut it here",
    "I placed a stop @ 1.05 on spy",
    "I took a little off at 1.29 here",
    "Stop hit on nvda, not much follow through here",
    "I’m selling some @  50% here",
    "Stop hit on the rest of nvda",
    "I’m selling some @ 45% here",
    "Fully out of apple here",
    "I sold some @ .28 here",
    "Stop hit on qqq here",
    "I scaled some at .69 here",
    "Stops hit on qqq here",
    "I’m getting out of Iwm. Looks like it’s not respecting the 13ema",
    "scaling some here @ 35%",
    "65% here on Iwm scaling some more",
    "Here’s the 13 break on Iwm I’m out of this play now",
    "nice break here, scaling at .55",
    "Scaled more @ 45% here",
    "Stop candle here, gotta protect gains",
    "I’m selling some @ .65 here",
    "I stopped on spy here",
    "b/e stop hit on Iwm. No follow through",
    "stop hit",
    "I’m selling amzn here",
    "locking some in here @ 25%",
    "45% on Iwm I’m scaling a little more here",
    "Taking most of my profits here over 55%",
    "Stopped out of all here",
    "Hit, too early here",
    "B/e stop in spy here",
    "New high on meta here. I’m scaling some at 25%",
    "Stop for the rest of my meta position I’d at break even",
    "I’m selling most at .73 here",
    "Didn’t get to scale in as we didn’t move up. Selling some at 20% here",
    "Scale some 176p @ 40%",
    "13 broke. Time to re assess",
    "scaling some here @ 25% on the zone break",
    "Scaling some @ 45% here",
    "80% on qqq here I’m trailing my stop",
    "I’m watching Iwm 185c",
    "I’m watching spy 394c",
    "Scaled some @ 1.05",
    "Hit 20% break even stop now",
    "New high of day here, scaling some at 1.50",
    "Stop hit here on spy for me. Had to lock in the gains 👊",
    "Taking some off of apple here @ 25%",
    "Stop hit on rest of apple here",
    "up 25% on this second apple trade I’m scaling some",
    "70% on that wick! Scale",
    "Stopped out",
    "13 broke, respect the stop leve",
    "Scaling some @ .77 here",
    "scaling some there over .50",
    "Stop hit here, the cons dipped to low to hold",
    "Scaled at .52 here",
    "Big move! Scaled some",
    "Stopped out here!",
    "trimming some Iwm here over 20%",
    "Stop above it",
    "Stop level hit here",
    "Stopped out on the rest, no follow through today",
    "Scaled some at .85 this time",
    "Stop hit here. 13 isn’t holding",
    "40% here selling half",
    "Scaling at .65 here",
    "I’m cutting Iwm here, not moving like I wanted it to",
    "30% here I’m scaling some",
    "Stop at break even on the rest",
    "took an early scale here @ .90",
    "another early scale on spy here @ .75",
    "over 30% here lock some in",
    "Locking some at 35% here",
    "Over 350% just trailing my stop",
    "Scaling now @ 40%",
    "Instant stop out on this one",
    "What a move! Scale some of you got in",
    "selling here on qqq chart still in tacked but the constructs are going against me",
    "Stop will be candle close over the 13ema",
    "Stop hit here on qqq",
    "Scaled some Iwm near 20% there",
    "Selling the rest of Iwm here",
    "Big push up and stop hit",
    "Stopping out of spy",
    "This pullback stopped me out",
    "Stopped out here",
    "Stopped out",
    "taking a small scale at .60 here",
    "Not holding, hit my stop",
    "I’m scaling some here @ 35%",
    "Level broke on nvda. Stop hit here",
    "scaling some here @28%",
    "Level not holding, selling qqq",
    "I’m out of qqq here",
    "I’m taking a little off here",
    "Really nice move . I’m out half for 40%",
    "I’m out most at our 200ema target 🎯 110%",
    "stopped out here",
    "stop hit here",
    "scaling some here on this drop",
    "selling the east here at even",
    "scaled some",
    "I’m out here",
    "I’m setting a 10% stop here",
    "Stop hit on half here",
    "This candle stopped me out. I’m out now",
    "I sold some here @ 20%",
    "I’m out a little more here on this new high of day for 50%",
    "I’m out here on qqq",
    "scaled some",
    "stop hit here",
    "I’m out here",
    "I sold a little at .60",
    "I’m stopped out here",
    "out half",
    "Took more off at .80 here",
    "stopped out here",
    "I’m out half @ 30%",
    "stop hit here!",
    "I’m out here",
    "I scaled half @ 30% here",
    "I’m out of spy here",
    "stopped .56",
    "qqq hit my stop here",
    "stopped out here",
    "I’m out here"
)

do_nothing = (
    "That’s a new high of day here",
    "New high of day on the break , looks good for that move",
    "This flag break will send us to 310 imo. Spy not even at the high of day yet",
    "I’m using that high of day level of 309.39 as my stop here",
    "Looks like we are heading for that 310 zone next",
    "We see the 3pm dip get bought up often",
    "Really close here! Up 50% on these",
    "Nice candle here",
    "Looking for that 309.39 level",
    "It’s late so the 0dte are wild",
    "Just sitting at my average here. Was hoping for a quicker move off the ema",
    "Taking the chance on some follow through here",
    "Stop is below the 13ema for me",
    "Spy also smoothing out now. I’ll be watching both on the pullbacks",
    "Exploded out of that flag! Was too slow on my entry. I’ll keep watching it",
    "It’s still really choppy",
    "Broke below the 200ema I’m watching this. It’s not an ideal setup so I’ll if I enter it will be with a smaller size position",
    "Hoping we smooth out here and ride the 13ema for a bit",
    "Sitting over 20% here should be easy to keep this trade green",
    "Nice candle",
    "I still have my eyes on that 394.40 level",
    "These conditions are not predictable",
    "Playing safe",
    "Hoping for some momentum to pick up",
    "I like the 13 crossing under the 200ema here",
    "Wicking hard here",
    "Seem to be holding under that 200ema here",
    "Nice flag break on spy. My main watch is below the 200ema here. I would like to catch a move down to the next support zone at 394.40",
    "I’m watching this dip on qqq to the 13ema",
    "I’m watching qqq 309c here if this flag break at the 13ema. Seems to be running a lot smoother now",
    "I’m watching spy 396p here if we break below the 200ema again",
    "I’m watching spy 395p here",
    "I’ll be watching spy 395p",
    "that flag has officially broke on qqq. I’ll be looking at pullbacks again here on the way up to that high of day level",
    "qqq is breaking out of a really nice bull flag here on the 5 minute. I’ll be watching 306c on the pullbacks",
    "I’ll be watching the 302p on the break under the 13ema",
    "Watching 303p",
    "still watching this lower flag line on qqq",
    "nice little bear flag forming in this zone on qqq. I’ll be watching 302p if it does break down out of this flag / zone",
    "spy breaking that trendline here. I’ll be watching   392p",
    "I’m watching qqq 301 puts here as we fall back under the 13ema",
    "I’ll be watching spy on this 13ema retest if it gives one",
    "I’m looking at the 388p",
    "I’m watching tsla 177.5p here",
    "I’m watching spy 387p here at the 13ema",
    "That was an ugly pullback, I’m still watching it",
    "I’m watching Iwm 171p as we flag back into the pre market low",
    "I’m still watching qqq",
    "nice bull flag break on the 15 minute qqq chart. I’m watching 306c again here",
    "watching the reaction to our 304 zone on qqq here",
    "I’m watching qqq 306c on this zone retest at the 13ema",
    "I’m watching amd 96c here",
    "watching this flag break on spy to re enter",
    "I’m watching the 390c",
    "spy breaking above our zone here. I’ll be watching the retest",
    "I’m watching qqq 298c here",
    "I’m watching qqq 297c here",
    "I’m watching spy 382p",
    "I’ll be watching spy 383p on this spy pullback to the 13ema",
    "I’m watching qqq 298c here on this pullback as we retest the high of day",
    "Im watching tsla 170p when we get back below the emas",
    "I’m watching qqq 297c here. We held support well here.",
    "I’m watching spy 387p here",
    "I’m watching spy 390p coming off this supply zone",
    "I’m watching qqq 298c here",
    "I’m watching qqq 298c if we hold above this intraday resistance zone",
    "I’m watching those same spy calls again",
    "’m watching qqq 294c here at the 13ema",
    "watching these Iwm puts again",
    "I’m watching Iwm 172p on the 13ema retest",
    "qqq held that zone really well. I’m watching the 295c again here",
    "Will watch the zone to hold here",
    "Still watching the pullbacks on this, I’ll be looking at the 295c",
    "Everyone I’m watching qqq 293c on this retest of the 13ema",
    "I’m watching Iwm 176p here",
    "I’ll be watching this flag break on spy to finish off this move to our zone",
    "I’m watching this area on spy to hold as resistance. We bounced off it 3 times this morning so I’m expecting it to hold now that we are under it",
    "Im watching spy 398p on the retest here",
    "I’m still watching these spy puts if we can hold under this zone",
    "I’m watching spy 399p on this bear break as well if we can clear this support zone",
    "I’m watching qqq 299p on the break of this bear flag",
    "Really nice channel break on spy here. I’ll be watching 397p if we can get below the 48ema",
    "I’m watching Iwm 186p here",
    "I’m watching spy 396p at the 48ema. 1dte",
    "spy broke through 399 support zone. I’m watching 398p on the pullbacks",
    "Just missed that entry, I’m watching 399p if we get that pullback to the 13ema",
    "nice flag /channel break on spy, below that 401.29 level again. I’m watching 400p here",
    "This isn’t really setting up very nicely. I’m gonna look for something with a better r/r",
    "Some major green bars coming in here. Flag not playing out. Will look for something better",
    "that’s an ugly candle. Not taking that lol",
    "I’m watching qqq 298c here",
    "Missed the fill on these, I’ll keep watching it though",
    "test",
    "I’m looking at the 388p",
    "my stop is set at ,68",
    "25% on nvda. Stop is raised into profit. Gonna let this work now.",
    "Amd at 1.05 here raise your stop to green",
    "keep a stop loss set below the 13ema",
    "1.20 on QQQ here protect your gains",
    "I have a hard stop at 1.10 now on these. Gonna try to let some of them run",
    "raise your stop to 1.40 of your still holding",
    "raising my stop to 1.50 here. 100% gain locked",
    "Stop is .95 on the rest of tsla. Keep the trade green",
    "keep a stop at -15% on these just incase",
    "10% keep stop at break even",
    "raise your stop on Iwm to .90",
    "Raising stop to 1.00",
    "raising stop to 1.10 on Iwm",
    "raising my stop again to 1.15 here on iwm",
    "50% here raise you stop up",
    "spy puts @ .86 here raise your stop to itm",
    "spy @ 50% here keep your stops up",
    "I’m watching those same spy 364p again",
    "Keep a stop above the 13ema",
    "watching qqq 269p here",
    "keep your stop in the money here. Don’t let it go red",
    ".65 here on qqq I’m trailing my stop tightly now",
    "I’m watching qqq 264p on this pullback",
    "Always raise your stops when we hit 25%",
    "I’m raising my stop on qqq as we go to protect gains",
    " I’m watching spy 359p",
    "Stop is above the PDL / 48 ema",
    "stop loss is .50 on spy",
    "were at 40% here on spy. Keep the stops raised",
    "watching Netflix 245c here",
    "Watching spy 357p here",
    "stop is 15% on spy",
    "50% here on spy! Protect your gains",
    " stop on spy is .55 now for me. We’re approaching 100% here",
    ".72 on spy here. .70 is my new stop for 100%",
    "I’m watching apple 145c here on this retest",
    "Keeping stop at 15% on these",
    "watching spy and qqq puts here",
    "keeping a 20% stop on these",
    "watching Iwm 165p here",
    "watching qqq 266c",
    "watching qqq 266c",
    "watching spy 356p here",
    "watching amd 60c here",
    "watching apple 144c here",
    "Now at .42 Keep a stop at the entry price",
    "Stop on the rest is .40 ",
    "Let’s ride this up if it wants go",
    "watching nvda 121c here",
    "My Stop is tight on these at .99",
    "watching amd 57p here",
    "Keeping a stop @ .50 on amd",
    "over 50% here on amd trailing my stop",
    "watching nvda 114p here",
    "Scratch these, wanted them to stay below 115 for entry",
    "watching qqq 261p here",
    ".75 here raise your stop to even",
    "watching spy 357p here",
    "I’m watching nvda 125c here",
    "watching Iwm 179c",
    "Stop under pm high level",
    "I will hold the rest for a break of that pm high level",
    "watching apple 148c here",
    "watching spy 365p off the 200ema",
    "Smaller size",
    "Stop is a break above the 200ema",
    "watching Iwm 170p on this retest",
    "qqq setting up here. I’m watching the 275c",
    "watching spy 366p",
    "Smaller size here",
    "15% here I’m watching this closely",
    "Keep a tight stop on these",
    "I’m gonna hold these until we break above the 13ema",
    "Stop for me is 1.00 on these",
    "apple nearing 1.20 here I’m placing my stop @ 1.05 for now",
    "I’m watching tsla 192.5p on a pullback",
    "new tsla average is 1.20",
    "Stop is 1.00 on these for me",
    "1.29 here on qqq raising my stop on half",
    "qqq @ 1.45 here watch for some support down here" ,
    "We’re touching demand here. Raise good stops on qqq",
    "Working out way down into this zone. Still letting it work",
    "We’re at 1.65 my new stop is 1.50 here. I think there is room for a big move here",
    "I’m watching apple 145c here",
    "I’m also watching spy 371c",
    "keeping qqq 273c on watch along with the others",
    "I’m watching Iwm 172c here",
    "I forgot to put the stop on Iwm in here",
    "I’m watching qqq 271p on this pullback",
    "I’m watching these same puts at the 48 as well",
    "I’m watching qqq 278c here",
    "I’m watching iwm 174c here as well",
    "Stop on Iwm is below this 173.19 level for me",
    "Working so far. I’m looking for a push up to the 174 area",
    "Here’s that push up, we’re at 40% here",
    "Watch this area here",
    "We’re at 25%",
    "If we break this zone 200ema is my target",
    "We’re flagging into this zone and emas about to cross up. We might see that 200ema tap here",
    "@ 35% on these and it’s looking good still",
    "Now just trailing my stop and watching for a 200ema bounce",
    "Use the 200ema as your risk if you take these",
    "I’m watching qqq 278c here",
    "My stop will be under 277.80 on these qqq calls",
    "70% here on qqq we’re looking over extended. Watch the pullback here",
    "Letting the rest ride this end of day move out",
    "I’m watching qqq 287c here",
    "Stop is below 13 ema",
    "qqq is near our average here be cautious on this one",
    "I’m watching amd 63c here",
    "Risk is the 13 ema on this one",
    "I’m watching spy 388c here",
    "I’m watching spy 380p here, risky as it will going against the trend so be cautious if you play it with me",
    "Crazy candle there! We’re up over 20% now and still looking for the 200ema",
    "30% on these puts now. 200ema target getting closer",
    "I’m watching Iwm 180c here",
    "I got filled @ .57",
    "Stop on this next round of Iwm is below the 13ema for me",
    "181c sorry",
    "I’m watching spy 385c here",
    "I’m watching spy 387c here",
    "We’re about to retest the pdh / 13ema",
    "I will re enter if it shapes up here after this candle, I don’t want to get knifed on",
    "My stop is 1.00",
    "I’m giving amd a chance to bounce on this line here",
    "1.15 here on amd I’m raising up my stop to green",
    "I’m looking for a test of 62 at that pdh",
    "The 48 could be a safer entry but we may not see it again.",
    "watching amd calls here",
    "I’m watching nvda off the 200ema",
    "For calls",
    "Stop is a close below the 200",
    "45% on nvda raise your stops",
    "Nvda over 50% here",
    "Amd still around 25%",
    "I’m watching spy 375p here",
    "Still watching it",
    "Stop is above the 200ema",
    "Keeping a stop above the 48ema on this",
    "I’m moving my stop to break even here on apple",
    "If the 13ema holds here we should be good for some continuation on apple",
    "we’re still up around 10% on apple I’m setting my stop on the rest of these at our entry price.",
    "Apple gearing up for the next leg down here imo",
    "We’re still up nicely and just letting it work",
    "Raising my stop on apple. We’re over 30% here",
    "I’m still just riding this apple move down as far as I can using the 13ema as my guide. We’re at about 50% gains now",
    "A little risky here imo",
    "But feel it’s worth a shot",
    "Took them on a close of this candle. My stop is a close above that same candle",
    "So far so good here, we’re at 1.27 on these and raising my stop to b/e",
    "Risk free trade at this point",
    "New low here on qqq we’re at 35% on these",
    "New stop level on qqq is above this flag / 13ema 👍",
    "I’m watching spy and qqq for retests to go long",
    "Being safe here",
    "These already hit 100%",
    "I’ll be watching for another entry",
    "Use the 13ema as your stop if it breaks",
    "They move quick",
    "Using the 200ema as my stop",
    "125% on tsla here 🔥",
    "I’m watching tsla 217.5 puts here",
    "Stop is above the 200ema",
    "35% here on tsla raising my stops",
    "Using the 200ema as my stop level",
    "My stop is .44 on the rest of these tsla cons",
    "I’m watching qqq puts here",
    "I’m watching tsla 227.5c here",
    "Using the 13ema as my stop",
    "What a candle",
    "I’m watching qqq 276p here",
    "Stop is a 200ema break",
    "I like these candles",
    "Raising stop on the rest",
    "Clean move down! Over 70% now on these puts",
    "these 275p are over 35% I’m raising my stop",
    "Now just riding the 13ema down on qqq here. Using it as my stop/risk level",
    "I’m watching qqq 276p here",
    "I was a little late",
    "I’m using the 48ema as my risk on this one",
    "Nice so far, we’re at .82 here",
    "I’m watching spy 385p here",
    "I’m watching qqq 278p here",
    "These just hit 20% if you were able to get in. Sorry I know that one moved fast. I’m raising my stop now",
    "I’m watching spy 389c here",
    "Tight stop on these",
    "Careful on these, my stop is set below this trend line",
    "I’m watching spy 385p on this pullback",
    "I’m taking these 385p here @ .59",
    "so far so good we’re @ .70 here",
    "Playing it safe",
    "Letting the rest ride with a break even stop now",
    "I’m watching Iwm 184c here",
    "I will use the 48ema as my stop on these",
    "Retest is holding so far but we are moving slow here",
    "What a knife!",
    "I’m watching Iwm  180p here",
    "I’m watching qqq 271p here",
    "A little risky here but I’m trying it",
    "Being cautious on this one. Will scale a little early at support",
    "We’re at 1.15  now",
    "Watching this close, above the 13 ema is my stop",
    "I’m giving qqq just a little longer to work here",
    "That support is right there and I expect a test of it",
    "We’re at that support level",
    "Holding this second half for a big move on the support break if we get it",
    "I’m watching spy 378p here",
    "Not quite at the 13ema but respecting this zone well",
    "qqq at 40%",
    "My stop in spy and qqq will be above the 13ema for now",
    "Will be watching to see how they react to the 48ema now",
    "I’m watching tsla 215p here",
    "Stop above the 13ema",
    "Pushing hard into the zone I’m cutting this early if it doesn’t wick",
    "I still like it but keeping the loss small here",
    "I’ll be watching qqq 270p at the 48ema",
    "Planning on scaling in on this one if we reach the 48ema",
    "here’s the 48 scale. Average is .95 now",
    "I will use a break of the 48 as my stop level",
    "Nice shove off the 48 ema here. Raising my stop to near break even here at around .90",
    "I would have liked it to hold the 13ema here. I’m gonna give it one more chance to break it",
    "We are sitting at b/e now",
    "It’s a coin flip at this point",
    "’m watching Iwm calls here",
    "Looking to hold this on gap level at 184.65",
    "my stop on this Iwm play is .68",
    "I’m watching qqq 269p here",
    "Play small with tight stop at .70",
    "Keeping it safe here",
    "I’m watching spy 377p here",
    "I’m watching msft 220p here",
    "Stop is tight at 1.20 on these",
    "Playing extremely cautious before the fomc meeting",
    "I’m watching Iwm 171p here",
    "I’m in watching qqq 256p here",
    "200ema play",
    "Stop right above it",
    "working well so far",
    "We’re near 20% place stops in the green",
    " I’m watching qqq 268c",
    "My target is a move up to this 265 level. Stop is below the 13ema",
    "New high of day here, looking good so far",
    "13ema is giving out here, have to respect my stop",
    "I’m watching Spx puts here. The 3665",
    "Playing smaller and gonna try to let them work",
    "We are gonna need a big move for these to pay nicely so play on the smaller side if your taking them",
    "My stop on this will be above the 48ema",
    "Level not holding on qqq",
    "If we close above I’ll stop out",
    "For now it’s still under it though",
    "Back under the 13ema now, looking good",
    "Working nicely now,",
    "We are getting wicky here qqq. Getting ready to sell the rest of these if we don’t push down",
    "I like the top wicks here on both spy and qqq",
    "I’m watching spy 378c here",
    "Waiting for the retest of the 13ema",
    "Stop is this candle close below the 13ema for me",
    "Giving it 1 chance to bounce here",
    "Letting it try to bounce here",
    "My stop will be no less than 1.00",
    "Will keep a stop above the 13/48",
    "We broke the lower trend line, and the 200ema. That’s why I took this",
    "We are back at 1.20 here",
    "I still have my stop at 1.05",
    "Finally breaking down a little here. Feel free to scale some in this chop. I’m holding",
    "Still holding most. Waiting for a real move down after all this chop",
    "I’m holding through this retest here",
    "Holding up well, back at 1.31 here",
    "Another retest here",
    "My stop will now be a lot 1.15",
    "No point in letting this one go red now. And that should be plenty of room to see if we get some continuation",
    "I’m watching spy 379c here on the pullback",
    "I’m watching nvda calls here also",
    "I’m watching qqq @ the 200ema here",
    "I’m watching nvda on a pullback here",
    "We’re over 20% on this flag break. Looking for some continuation on this one",
    "We hit 30% on this new high",
    "Watching for this high to hold on Iwm",
    "If we lose this level I will exit",
    "Using the 48ema as my stop level on nvda",
    "I’m watching apple 136p here",
    "My stop is above the 13ema on these",
    "Raising stops",
    "60% here on apple be safe",
    "Qqq and spy breaking the 200ema as well. We should see some more downside here",
    "The next break to watch",
    "Nice, 70% here on apple now",
    "were @150% here raising stops",
    "Running nicely now",
    "No green candles, we’re close to 300% here",
    "Next leg down to watch",
    "Nice! That break out is well over 300% on these contracts",
    "Watching closely here for the 13ema exit",
    "Incase we bounce off the 13ema",
    "Still holding here",
    "48 holding well. We’re @ 40% here",
    "120% here watch this zone",
    "Scaled some on the bounce. Holding for a new low of day now",
    "One more level then new low of day coming on qqq",
    "We’re @ 130% here",
    "Level breaking! We’re at 150%",
    "Candle closing under the 13ema , I’m holding",
    "Level testing again here",
    "Should break this time",
    "What a candle out of that zone!",
    "What a stop candle! Here that low of day now. No complaints, holding through would have been risky. Getting volatile here",
    "I’m watching Iwm on this pullback",
    "watching qqq 262p here",
    "Looking for a break here",
    "Up 12% already, will scale some at 20%",
    "I will use the 200ema as my stop",
    "Using the 13ema as my stop level now",
    "Still using the 13 as my stop",
    "Tapping 80% here. Just riding the 13ema",
    "Iwm working great. Watching the 13ema here and will stop out if it breaks above it",
    "No break yet = let the winners run",
    "95% here, letting it work",
    "I’m watching Iwm 178p here",
    "@.45",
    "Stop on Iwm is above the 13/48",
    "Getting some nice follow through here. We’re over 30%",
    "Playing safe, it’s still a little choppy out there",
    "Watching the retest. I’m expecting some continuation here",
    "I will use the 13 as my stop, if it hits I will look at the 48 to re enter",
    "35% I’m raising my stop",
    "Just watching the 13ema here for continuation",
    "We’re back at our entry here, I’m still in",
    "Will exit on the break of the 13ema",
    "I’m gonna watch the 48 ema on spy and qqq for a re entry spot",
    "My stop will be the 48ema on these",
    "We’re at .90 here. Stops gonna be at break even for a risk free chance at a nice move into close",
    "I’m watching tsla 175p here",
    "I’m watching Amazon 87p here also",
    "Tight stop above the 13ema",
    "We may push up here",
    "Will watch it on a deeper pullback",
    "sorry I meant amzn 87p on these",
    "Gonna re evaluate",
    "I’m watching apple 135p here",
    "Just watching",
    "I’m watching Iwm 182c here",
    "I’m keeping my stop below that 180.57 level",
    "Little break out here",
    "Some nice follow through on this one. At 30% now",
    "Just letting it ride the 13ema",
    "Flag retest",
    "Watch for bottom wicks for continuation",
    "Nhod on Iwm",
    "I’m watching qqq 275c",
    "Flag broke. We are over 1.20 already on these",
    "Just need it to hold",
    "Stop will be the 13ema on these",
    "Should retest and go imo. Can scale to be safe",
    "Here’s the retest. Keep stops at break even",
    "May have been a little wary on the flag break but looks like we are going to get a nice move here soon. I’m still watching calls on spy and qqq",
    "Same spot as before. Stop set below the 13ema",
    "Looking for a new high of day here. Possibly after a 13ema retest",
    "Letting this candle close here. The position is only down 5%",
    "I’m watching Iwm 176p here",
    "It’s early so maybe a smaller size play",
    "Stop above the 13",
    "I’m watching spy 377p here",
    "200 ema play",
    "Stops above it",
    "20% here on meta",
    "Risk is that level above",
    "The levels holding but not as perfect as I wanted",
    "Looking choppy",
    "Stopped out on the rest",
    "Strong wicks on the trendline",
    "Watch this zone now. We are approaching it with some volume",
    "Top wicks at the zone",
    "Looks good",
    "40% here on iwm. Still looks good imo",
    "Over 60% now. We are through the zone",
    "More volume coming in below this level",
    "75% here I’m holding. We are looking weak",
    "Leaving room for the 13 ema retest",
    "Good r/r for another entry", 
    "Perfect re entry spot",
    "Over 100% on Iwm",
    "I filled @ .22",
    "Another great r/r add there. 30% here",
    "Will stop out of everything above the 13ema",
    "Playing smaller here",
    "Will let it ride a little loose with the stop",
    "We might get wicky on the zone break",
    "Almost 20% here",
    "Play it safe on this one",
    "Letting the rest ride with break even stop",
    "Nice move! Over 30% here",
    "approaching support here",
    "Another 100% play here 🔥",
    "135% setting my stop at 1.60",
    "Stop is a candle close above it",
    "20% here on qqq keep it green if you took it",
    "Over 50% on qqq here. Letting it ride",
    "I’m watching spy 394c now that we’re breaking this level",
    "May test 190.69 here. My stop is below it",
    "Working good, at 1.42 here",
    "I’m watching spy 395c at the same level",
    "I’m watching this Iwm setup for puts",
    "I’m watching apple 143p",
    "Playing safe near open",
    "These are at my average here",
    "I’m watching Iwm 189c here",
    "Stop out will be candle close below 13ema",
    "I’m watching qqq 287c here on the pullback",
    "The reason for the scale was the pm high resistance",
    "Now we hold and see if it breaks",
    "Above the level now and up nicely!",
    "Will this position as long as we are above the 13ema",
    "Looking for this level to hold. If it breaks I will exit",
    "Holding the rest for this level",
    "I’m watching tsla 192.5c",
    "Looking to enter on this trendline pullback at the 200ema",
    "1.30 on this push up, I’m holding",
    "Here’s the 200 retest, looking for it to hold",
    "Make or break spot on tsla here",
    "Spy needs to show a little strength here and we’re good",
    "Breaking out now",
    "tsla is @ 40% Keep it green",
    "I will be holding some for a test of that 195 level above",
    "I think we get some momentum here",
    "Spy above the 200ema now",
    "We’re coiled up here just waiting for the 13ema to catch up",
    "50% on tsla now",
    "Here the pullback. I’m risking the 13 ema break here for some more continuation",
    "Spy holding the 200ema as well",
    "Bullish signs",
    "I’m watching spy calls here",
    "Only risking this level on spy",
    "Will stop out below this level",
    "Holding",
    "High of day here. Stop at break even now",
    "Another high there, cons @ .60 here",
    "Looking for a nice move here off this",
    "I’m watching Iwm 184p for a smaller sized play here",
    "Letting Iwm work itself below this level",
    "@everyonr 40% on Iwm here keep it green",
    "I’m watching qqq 284p here",
    "Stop is above 285.50 on qqq",
    "Testing that level now",
    "I’m watching qqq 288c here",
    "I’m watching qqq 284p",
    "Stop loss above the 13ema",
    "Stop below the 13",
    "Selling some on this push up @ .82",
    "Over 20% here keep it green. Still choppy out there",
    "New highs here",
    "watching qqq calls again here",
    "The 289c this time",
    "30% push here lock some more",
    "Stop below the 13ema for the rest of these qqq calls",
    "I’m watching spy 400c here",
    "Smaller size on these if I play them",
    "I’m watching this pullback for the 400c on spy",
    "Cleared the pdh I’m watching the pullback",
    "Up 10% here",
    "Looking for a nice push up here",
    "Went +15 to -10 here im holding for now",
    "Watching for the break out here",
    "I will cut these if we don’t get it",
    "We’re trying",
    "Looking for a strong break of 400 here",
    "Stop below the 48ema",
    "Quick bounce scalp",
    "15% here break even stop set!",
    "200ema target on these",
    "Tapping .12 there I’m holding for the 200ema",
    "Spy not helping out cause but the emas are holding up",
    "Bearish ema cross here",
    "200ema target hitting 35% here",
    "200ema 🎯 over 50% now",
    "If we lose the 200ema the rest of these are gonna pay nice",
    "Break even stop on the rest",
    "I’m watching Iwm 191c",
    "Watching this candle on it",
    "Will have my stop below the 13ema",
    "Held pm high so looking good imo",
    "Will wait out this spy chop now before taking anything else",
    "I’m watching qqq 290p",
    "Risking the 48ema here. Stop above it",
    "Will exit this play if we break the 48",
    "I’m watching spy 399p",
    "Playing safe",
    "Now letting it ride",
    "Pdh showing resistance",
    "It’s still choppy",
    "Qqq hanging us up here at the 200ema",
    "Stop above the 48ema now",
    "I will stay in as long as we are below the pdh",
    "Holding under the pdh on the 15",
    "Another 20% here",
    "Make that 30 🔥",
    "80% here on spy",
    "almost 200% on spy here",
    "230%",
    "Risky being so low already",
    "Looking for a wick here",
    "Got the wick",
    "Over 20% here",
    "Im holding for a nice move down, but feel free to scale",
    "Down more than I’d like to be on this qqq play but still holding",
    "Didn’t scale at 20% now down 20%",
    "Still looking for a move towards 284 here to finish it off",
    "Over 50% here and not letting it go back red now lol",
    "Over 50% here and not letting it go back red now lol",
    "284p",
    "Risking the 13ema break.",
    "I’m watching Iwm 185p when we get a pullback going it",
    "I’m watching spy 394p",
    "I’m watching qqq puts as well",
    "Stop will be candle close over the 13ema",
    "A little support at PDL here",
    "Should move nicely if we clear it",
    "Struggling a little at this level",
    "Bounced off PDL",
    "Same thing, stop is candle close over the 13ema",
    "Will re assess",
    "I’m watching qqq 284p again here",
    "Here’s what I’m seeing",
    "Stop loss above that 286 level",
    "Push up to that level here, watching for a wick",
    "No wick but respecting the level",
    "Need spy to hold this zone here",
    "Still at break even here",
    "Up 10% but still in a sketchy area",
    "I’m watching qqq 284p on the pullback to the 13ema",
    "Will play smaller on this one with the ema spacing not being great",
    "Ugly pullback here. Waiting it out",
    "I’m watching spy 399c",
    "Wicking hard here be careful",
    "Not holding the 200 ema here I’m cutting here near my average",
    "I’m watching Iwm 184p on this pullback",
    "Retest holding so far. Up 10%",
    "No scale yet for me",
    "Will hold as long as we hold the 13ema",
    "Still working, approaching that 20% mark here",
    "Here it is, over 20%",
    "Grinding down here slowly",
    "35% here",
    "Gonna ride this down as far as it takes me with the 13ema",
    "Still riding it. At 40% now",
    "Stop is gonna be that 286 level for me",
    "Nice candle, up 10%",
    "Holding for that follow through here",
    "No follow through again",
    "I’m watching spy 390p 1dte",
    "Working so far",
    "15% here",
    "Still green here, letting it test the 48ema",
    "Will stop out over the 48 ema if it breaks on this spy play",
    "So far it’s holding nicely",
    "I’m watching nvda 152.5p here",
    "Just so I won’t stop our red if we revers here",
    "Should see resistance here",
    "Will watch for a re entry",
    "Level was reclaimed",
    "Will use the 13ema as my stop on the rest",
    "I’m watching amd  73p here",
    "13ema stop on the rest for me. Stress free here",
    "60% on amd here if you held through that pullback",
    "fresh lows here on amd",
    "Up to 80% on these",
    "I’m watching qqq 282p here",
    "Still holding amd as well",
    "Stop is above this 13ema level on qqq",
    "Will look to re enter",
    "Same with amd",
    "watching spy puts here",
    "Stop on this one is above the 200ema",
    "@ .43 here on spy, play it safe in this area",
    "I’m watching qqq 301 puts here as we fall back under the 13ema",
    "I’m using a break over the 13ema as my stop loss here",
    ".69 here, I want to see a pml test",
    "Still in a little bit of a choppy area will look to scale some out on a drop",
    "Thinking I may have jumped the gun on that one. Spy was not showing enough weakness to let qqq drop",
    "A break even stop should have been set there for me",
    "spy is sitting right in our first supply zone. I want to see a break up over this zone before going long. Or a break down under this lower trend line before going short.",
    "spy breaking that trendline here. I’ll be watching   392p",
    "Closes below the trend line and 13ema here so I’ll use that as my stop",
    "Between the emas here so will look to scale out at the 48ema first",
    "Playing it safe",
    "Between the emas can get choppy so just want to keep it green here",
    "The overall outlook looks bearish",
    "Rejected supply and broke trend",
    "Nice push here, up 25%",
    "A close below the 48ema would be nice here",
    "Under the 48ema now. Good sign",
    "Would like to see a 200ema test here",
    "200ema is at 391.44",
    "Picture perfect wedge break out of the supply zone",
    "Bouncing a little off the new low. Hoping for a flag break here",
    "Emas about to cross up",
    "Flag breaking here, siting @ 50% now.",
    "Tight stop on the rest incase we bounce here",
    "Wow no bounce. Straight to 180% on the runners 🔥",
    "Now that we are below the 200ema I’ll use that as my stop on these runners.",
    "crazy wick on that candle actually showing it didn’t break out of the flag",
    "Spy rejecting the supply zone again",
    "Looking for that new of day here. Will stop out below the 13ema",
    "Spy at supply zone so I played it small",
    "Keep that in main",
    "Mind",
    "This is on the risky side with spy at supply zone",
    "Going long before the supply zone break on spy is a risky trade. I played it small because of this but still not a smart play there",
    "Nice flag break on spy. My main watch is below the 200ema here. I would like to catch a move down to the next support zone at 394.40",
    "I’ll be watching spy 395p",
    "Seem to be holding under that 200ema here",
    "Wicking hard here",
    "Rest",
    "I’m watching spy 395p here",
    "I like the 13 crossing under the 200ema here",
    "Hoping for some momentum to pick up",
    "Playing safe",
    "These conditions are not predictable",
    "I still have my eyes on that 394.40 level",
    "Nice candle",
    "Sitting over 20% here should be easy to keep this trade green",
    "Hoping we smooth out here and ride the 13ema for a bit",
    "I’m watching spy 396p here if we break below the 200ema again",
    "Broke below the 200ema I’m watching this. It’s not an ideal setup so I’ll if I enter it will be with a smaller size position",
    "It’s still really choppy",
    "This isn’t really setting up very nicely. I’m gonna look for something with a better r/r",
    "I’m watching qqq 309c here if this flag break at the 13ema. Seems to be running a lot smoother now",
    "Exploded out of that flag! Was too slow on my entry. I’ll keep watching it",
    "Spy also smoothing out now. I’ll be watching both on the pullbacks",
    "Stop is below the 13ema for me",
    "Taking the chance on some follow through here",
    "Just sitting at my average here. Was hoping for a quicker move off the ema",
    "I’m watching this dip on qqq to the 13ema",
    "It’s late so the 0dte are wild",
    "Looking for that 309.39 level",
    "Nice candle here",
    "Really close here! Up 50% on these",
    "We see the 3pm dip get bought up often",
    "Here’s that level! Took more off at 100%",
    "That’s a new high of day here",
    "Looks like we are heading for that 310 zone next",
    "I’m using that high of day level of 309.39 as my stop here",
    "150% here on the way to that 310.10 zone",
    "This flag break will send us to 310 imo. Spy not even at the high of day yet",
    "New high of day on the break , looks good for that move",
    "There’s 310 🎯 over 200% now",
    "We are just ranging between 2 support and resistance zone here on qqq. I’ll be waiting for a break of one or the other before looking for an entry. Below 310 I’ll look for puts. Above 314 I’ll look for calls 👍",
    "nice break over 314 on qqq. I’ll be watching 316c on the pullback",
    "Still have to play it safe with powell speaking. The market will react to what he has to say",
    "They are not liking what he is saying. Gonna have to wait until he is finished to get an entry on anything that’s not a compete lotto",
    "first day in a really long time I didn’t get a trade in. A couple decent moves went down last minute there but overall not much as far as A+ r/r setups for me. Looking forward to the end of the week 🤙",
    "we are basing on top of that pre market high nicely. I’ll be watching 397c on spy",
    "I like qqq here above our zone also",
    "Watching the 312c here",
    "13ema stop for me here",
    "A new high of day would be nice here",
    "I’m watching qqq 312p for a scalp down to the 48ema",
    "Rejected that zone well so thinking we at least see a deeper pullback to the 48ema here",
    "I don’t like to fight the trend so I’ll scale out some here quickly",
    "If 314 was the top these will be really nice. Needs to stay under the 13ema now",
    "Looks like maybe the trend wants to continue",
    "I’m watching spy 400c here",
    "Looks like we could see more upside soon",
    "Just have to avoid the chop",
    "adjusted this channel a little. Looks almost ready for me",
    "I’m watching those 400c still",
    "I’ll use the 13ema break as my stop here",
    "It’s a little risky to time but the r/r is there for me",
    "13ema curling up a little here as well",
    "Qqq at supply zone making it risky",
    "Broke the ema",
    "I’m gonna be a little more patient and wait for a clear direction here. We are kind of trapped between resistance and the emas after the big move up.",
    "I’m watching spy 394p on this retest of the 13ema",
    "Really close to that zone so playing it smaller",
    "I need to see it hold under this level",
    "I’m playing it safe near this zone",
    "Needs a solid break here",
    "Was really trying to hold that pm level but couldn’t do it",
    "Moving quickly here",
    "Think we see that move down to our zone now",
    "We have a little bigger trend line break now",
    "Maybe double bottom here",
    "Really volatile area here on the contracts",
    "Went 35% back to me entry, I’m holding for that move into the zone here",
    "Now at 40% as we head for that zone tap",
    "sitting around .70 here. These are fluctuating a lot. Scale and stay safe",
    "Hoping for one nice push down deep into this zone",
    "If we continue to look weak I’ll get back in",
    "qqq breaking down below our zone here. I’ll be watching the pullbacks on it",
    "Same for Iwm, finally breaking that 170",
    "Watching these pullbacks on spy on qqq here",
    "I’m watching spy 390p on this 13ema pullback",
    "Will keep a tight stop over this zone",
    "I’ll stop out of the rest over this zone",
    "Needs to hold the 48ema here",
    "60% here as we break below the 13ema now",
    "Zone held really well! 75% on these",
    "Just needs to hold under the 13ema here and we should see a new low of day",
    "Nice! New lows and 160% now",
    "I’m out most there as we approach that 390  level",
    "really choppy conditions so far. Forcing me to wait for a range break here. Taking anything before that is gonna be a lot higher risk",
    "I’m watching spy 388p here",
    "Will keep the 20% stop on these",
    "Not breaking down here",
    "I’m warning spy 395c here",
    "13ema stop loss for me here",
    "Would like to see a move to a new high day",
    "No follow through",
    "If we pick back up I’ll re enter",
    "I’m watching this flag break to possible bring in some upside momentum on spy. I’ll be looking at those same 395c",
    "Definitely brought the momentum. I’ll be watching pullbacks",
    "Risky pullback",
    "I’m gonna try it",
    "Stop under 13ema",
    "The contracts dropped so much on that pullback I liked the r/r there.",
    "Finally breaking this zone and wicked the 13ema",
    "Wow that was a 40% candle there",
    "3pm always gets volatile",
    "Spy at the pre market high is holding this back",
    "Basing well on this zone",
    "New high of day, we need a breakout here",
    "I’m gonna watch spy now",
    "That qqq trade hit 60% so will play it cautious here and not give it right back",
    "It’s gonna get all wicky at 3pm",
    "I’m watching qqq 310c again here",
    "Risky",
    "Time of day is not ideal here",
    "I want to see us hold above the 13ema here",
    "We seem to be holding above that major intraday resistance",
    ".70 here",
    "Can scale to reduce the risk",
    "qqq holding that zone really well. I’m watching it",
    "Perfect breakout and retest of that intraday resistance zone. I’ll be watching pullbacks if we get any",
    "Late day plays always add risk but I like it",
    "Perfect bounce here. Over 1.00 now. Should be easy to keep it green and ride it into close",
    "Slow and steady so far",
    "just watching this 13ema as my stop level",
    "We’ve bounced to 15% a couple times so I took some off to play it safe and not go red on that stop",
    "I don’t r want to bail out right before a possible move up to end the day",
    "Horrible price action to end the week but we survived lol. Overall a good week and looking forward to Monday already. Have a great weekend everyone! 🤙",
    "New lows! 60% here"
)

buy_and_sell = (
    "my stop hit and I’m back in spy 399p @ .66"
)


"""
LEFT OFF AT:
   search bar (in: 🚨-trades )
   message id: 
"""


def replace_right_quotes(s):
    return s.replace('\u2019', "'")

data = []

for group, label in [(buy, "buy"), (sell, "sell"), (do_nothing, "do_nothing")]:
    for message in group:
        message = replace_right_quotes(message)
        data.append({"message": message, "label": label})

with open("dataset.json", "w") as f:
    json.dump(data, f, indent=2)
